const ACTION_TYPES = {
    LOGIN: 'LOGIN',
    SET_USER_NAME: 'SET_USER_NAME',
    SET_GAME_SETTINGS: 'SET_GAME_SETTINGS',
    FETCH_QUESTIONS_REQUEST: 'FETCH_QUESTIONS_REQUEST',
    FETCH_QUESTIONS_SUCCESS: 'FETCH_QUESTIONS_SUCCESS',
    FETCH_QUESTIONS_FAILURE: 'FETCH_QUESTIONS_FAILURE',
    STARTED_TRIVIA: 'STARTED_TRIVIA',
    QUESTION_ANSWERED: 'QUESTION_ANSWERED',
    FINISHED_TRIVIA: 'FINISHED_TRIVIA',
    CLEAN_ANSWERS: 'CLEAN_ANSWERS',   
}

export default ACTION_TYPES;